### ISSUE TITLE
JWT 기반 인증 및 인가 기능 구현

### ISSUE THREAD

**Issue by JangWooJin1** [pda5th-TheOne/backend#11]
## Description

Spring Security와 JWT를 이용한 인증/인가 기능 구현.

## Todo

- [x] **User 엔티티 및 리포지토리 생성**  
  - 사용자 데이터 관리 (이메일 기반 조회 포함).
  
- [x] **UserPrincipal 및 CustomUserDetailsService 구현**  
  - Spring Security 인증 사용자 로드 및 권한 설정.

- [x] **JwtUtil 클래스 구현**  
  - JWT 생성, 검증, 사용자 정보 추출.

- [x] **JwtRequestFilter 작성**  
  - 요청에서 JWT 추출 및 검증, SecurityContext 설정.

- [x] **Spring Security 설정**  
  - 필터 체인 설정, 세션 Stateless 모드, 엔드포인트 접근 제어.

- [x] **인증 컨트롤러 작성**  
  - 로그인 API로 JWT 발급 및 토큰 검증 API 제공.
