### ISSUE TITLE
핵심 데이터베이스 엔티티 및 관계 구현

### ISSUE THREAD

**Issue by JangWooJin1** [pda5th-TheOne/backend#13]
## Description

- 데이터베이스 관련 엔티티 구현
- 주요 엔티티:
  - `DailyBoard`: 게시판 관리
  - `Practice`: 실습 문제 관리
  - `TIL`: 오늘 배운 내용 기록
  - `Question`: 질문 댓글
  - `Reply`: 답글
  - `UsersPractices`: 실습 완료 사용자 기록
  - `HoneyUsers`: 목표 달성 기록
  - `HoneyGoals`: 목표 설정

## Todo

- [x] `DailyBoard` 엔티티 구현
- [x] `Practice` 엔티티 구현
- [x] `TIL` 엔티티 구현
- [x] `Question` 엔티티 구현
- [x] `Reply` 엔티티 구현
- [x] `UsersPractices` 엔티티 구현
- [x] `HoneyUsers` 엔티티 구현
- [x] `HoneyGoals` 엔티티 구현
