### ISSUE TITLE
실습 상세페이지 API 구현

### ISSUE THREAD

**Issue by JangWooJin1** [pda5th-TheOne/backend#17]
## Description
- 실습 상세페이지를 위한 CRUD API를 구현
- 특정 실습에 대한 상세 정보 조회, 문제 및 모범답안 수정, 사용자 완료 상태 관리 기능을 제공

## Todo

- [x] 전체 실습 상세 조회 API 구현 (GET: `api/practices/<id>`)
- [x] 문제 수정 API 구현 (PUT: `api/practices/<id>/assignment`)
- [x] 모범답안 수정 API 구현 (PUT: `api/practices/<id>/answer`)
- [x] 사용자 완료 상태 등록 API 구현 (POST: `api/practices/<id>/users_practices`)
- [x] 사용자 완료 상태 삭제 API 구현 (DELETE: `api/practices/<id>/users_practices`)
