### ISSUE TITLE
특정 보드 내 실습 관련 CRUD API를 구현

### ISSUE THREAD

**Issue by alstjs37** [pda5th-TheOne/backend#26]
## Description

- 특정 보드 내 실습 관련 CRUD API를 구현

## Todo

- [x] 한 게시판에 대한 전체 실습 조회 API 구현 (GET: api/boards/{id}/practices)
- [x] 실습 ADD 버튼을 통한 실습추가 API 구현 (POST: api/boards/{id}/practices)
- [x] 실습(제목) 수정 API 구현(PUT: api/practice/{id})
- [x] 실습(제목) 삭제 API 구현(DELETE: api/practie/{id})
