### ISSUE TITLE
타이머 기능 구현을 위한 Server-Sent Events (SSE) 도입

### ISSUE THREAD

**Issue by JangWooJin1** [pda5th-TheOne/backend#28]
## Description

타이머 기능을 구현하기 위해 여러 브라우저에서 동일한 타이머 상태를 실시간으로 공유할 수 있도록 Server-Sent Events (SSE)를 사용
이를 통해 사용자는 타이머 상태를 실시간으로 업데이트하고, 다른 브라우저에서도 동일한 상태를 확인 가능

## Todo

- [x] SSE를 사용하여 타이머 상태를 실시간으로 스트리밍하는 기능 구현
- [x] 타이머 시작, 일시정지, 재개, 리셋 API 엔드포인트 구현
- [x] 타이머 상태 변경 시 모든 연결된 클라이언트에 업데이트 전송
- [x] Swagger 문서에 SSE 및 타이머 API 설명 추가
