### ISSUE TITLE
JWT 인증 및 질문 큐 SSE 구현

### ISSUE THREAD

**Issue by JangWooJin1** [pda5th-TheOne/backend#30]
## **Description**

- 질문 큐에서 **사용자 상태 관리 및 SSE(서버 전송 이벤트) 구현**.
- JWT를 통한 **유저 인증** 및 **질문 큐 실시간 업데이트** 기능 추가
- 질문 큐에서 **손들기/손내리기** 동작을 처리하는 RESTful API 구축

## **Todo**

- **JWT 인증 API** `/validate-token` 구현:
  - [ ]사용자 토큰을 검증하고 **유저 정보(id, name)**를 반환.
  
- **질문 큐 API**:
  - [x] `GET /api/questions`: 현재 질문 큐 상태를 반환.
  - [x] `POST /api/questions`: **손들기 요청**으로 큐에 사용자 추가.
  - [x] `DELETE /api/questions`: **손내리기 요청**으로 큐에서 사용자 제거.

- **SSE(Server-Sent Events)** 구현:
  - [x] `GET /api/questions/stream`: 질문 큐의 실시간 업데이트를 클라이언트에 스트리밍.
