### ISSUE TITLE
실습 상세 페이지 오류 수정 - 문제 저장 및 제출 중복 방지

### ISSUE THREAD

**Issue by JangWooJin1** [pda5th-TheOne/backend#37]
## Description

1. 문제 내용 저장 시 이슈
- 문제 내용 저장 시, 프론트에서 전달된 값에  **("")** 이 포함되어 저장되는 문제 발생
- 이를 해결하기 위해 기존 `String` 타입으로 요청을 받던 방식을 **DTO**(`PracticeUpdateRequest`)를 사용하여 데이터 구조를 명확히 전달하도록 변경.

2. 제출 완료 시 중복 저장 이슈
- 사용자가 실습 상세 페이지에서 **제출 완료**를 여러 번 누르면 동일한 유저와 실습 데이터가 중복으로 저장되는 문제가 발생.
- 이를 방지하기 위해 **엔티티에 유니크 속성**을 추가하여 중복 데이터를 저장하지 않도록 처리.

## Todo

- [x] `PracticeUpdateRequest` DTO로 요청 데이터 구조 변경 확인.
- [x] 엔티티에 유니크 속성 추가로 중복 저장 방지 테스트.
- [x] 실습 상세 페이지에서 제출 기능 정상 동작 확인.
